### ISSUE TITLE
Exclamation marks - top right corner, wallet not loading..

### ISSUE THREAD

**Issue by time-dj** [tchoulihan/bitmerchant#3]
Here is what the issue looks like. The wallet isnt loading .. im not seeing the 12 words and the wallet link and the settings link produce the exclamation marks.

http://i.imgur.com/Y7JwNlo.jpg

I tried without the loglevel parameter first and then with like below but no joy...
" java -jar bitmerchant-shaded.jar -loglevel info"

Im a bit green so im posting the actions i took that got me here just in case im missing something.

I ultimately signed up for a vps at digital ocean. I created the droplet and used ubuntu.

After setting up putty i logged in and installed java with this:

"sudo add-apt-repository ppa:webupd8team/java 
sudo apt-get update
sudo apt-get install oracle-java8-installer"

Then i installed maven with:

sudo apt-get update sudo apt-get install maven

After that i downloaded the jar file... "wget https://github.com/tchoulihan/bitmerchant/releases/download/v1.2/bitmerchant-shaded.jar"

The i ran the start command ...
"java -jar bitmerchant-shaded.jar"

Then i turned on chrome and typed in my server ip in the address bar followed by the port number:
Example xxx.xxx.xxx.xxx:4567

Page loads but i get the error mention above and no wallet of course.

I tried again with the loglevel parameter like the below but no joy!:
" java -jar bitmerchant-shaded.jar -loglevel info"

Also cant get this to work at all.. "./run.sh"

Here is the output below: Thanks in advance.
***************************************************************

Edited (output removed)

**Comment by tchoulihan** [comment]
Okay, the problem is that you're trying to access your wallet over the internet. For obvious reasons, this is blocked(you don't want anyone able to type that ip in to be able to access your wallet do you?)

The only way to access your wallet is to VNC to that machine, and open http://localhost:4567/ up in a browser, as I said in the initial instructions. 

I'm using digital ocean too, so I used [these](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-vnc-on-ubuntu-14-04) instructions to get that up and running. Make sure you enable ssh too, and your vnc client can tunnel through ssh. Digital ocean has plenty of instructions for how to do this.

I thought about providing some sort of user login, but decided it was too much of a security risk.

**Comment by tchoulihan** [comment]
Also, if you'd like to test it out on your development machine first, everything is functional, as long as you're accessing it from localhost.

**Comment by time-dj** [comment]
Ah.. makes sense.. I dunno what made me think i could just use the ip and port number. I followed the tutorial on digital ocean to setup the vnc server but on step four where i needed to setup the forwarding to the local host connection for vnc i got some error that said address already binded.  It was 5am and i was winding down a long day so i will retrace my steps and see what i can find.. 

Thanks,
Time_dj

**Comment by tchoulihan** [comment]
No problem. Let me know if you have any other questions.
